# Generated by Django 6.1.1 on 2026-09-19 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute', models.CharField(max_length=200, null=True)),
                ('education_type', models.CharField(blank=True, max_length=50, null=True)),
                ('degree_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_marks', models.FloatField(blank=True, null=True)),
                ('obtain_marks', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducatedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(null=True)),
                ('skills', models.TextField(null=True)),
                ('experience', models.FloatField(default=0.0)),
                ('github', models.URLField(null=True)),
                ('linkdin', models.URLField(null=True)),
                ('other', models.URLField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educated_category', to='user_profile.category')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educated_user', to=settings.AUTH_USER_MODEL)),
                ('education', models.ManyToManyField(blank=True, null=True, related_name='provider_education', to='user_profile.education')),
            ],
        ),
        migrations.CreateModel(
            name='UneducatedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(null=True)),
                ('experience', models.FloatField(default=0.0)),
                ('description', models.TextField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uneducated_category', to='user_profile.category')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uneducated_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
