# Generated by Django 6.1.1 on 2026-09-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatedprofile',
            name='education',
            field=models.ManyToManyField(blank=True, related_name='provider_education', to='user_profile.education'),
        ),
    ]
