# Generated by Django 6.1.1 on 2026-10-01 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_educatedprofile_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='UneducationalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='EducationalCategory',
        ),
        migrations.AlterField(
            model_name='uneducatedprofile',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uneducated_category', to='user_profile.uneducationalcategory'),
        ),
    ]
